<link rel="stylesheet" type="text/css" href="{{url('css/bootstrap.min.css')}}">
<link rel="stylesheet" type="text/css" href="{{url('css/bootstrap-grid.min.css')}}">
<link rel="stylesheet" type="text/css" href="{{url('css/bootstrap-reboot.min.css')}}">
<link rel="stylesheet" type="text/css" href="{{url('css/datatables.min.css')}}">
<link rel="stylesheet" type="text/css" href="{{url('css/jquery-ui.min.css')}}">
<link rel="stylesheet" type="text/css" href="{{url('css/responsive.bootstrap4.min.css')}}">
<link rel="stylesheet" type="text/css" href="{{url('css/style.css')}}">
<link rel="stylesheet" type="text/css" href="{{url('css/fa-brands.min.css')}}">
<link rel="stylesheet" type="text/css" href="{{url('css/fa-regular.min.css')}}">
<link rel="stylesheet" type="text/css" href="{{url('css/fa-solid.min.css')}}">
<link rel="stylesheet" type="text/css" href="{{url('css/fontawesome.min.css')}}">
<link rel="stylesheet" type="text/css" href="{{url('/css/fontawesome-all.min.css')}}">
<link rel="stylesheet" type="text/css" href="{{url('/css/bootstrap-datetimepicker.min.css')}}">
<script src="{{url('/js/jquery.min.js')}}" type="text/javascript" charset="utf-8"></script>
<script src="{{url('/js/jquery.mask.min.js')}}" type="text/javascript" charset="utf-8"></script>
<script src="{{url('js/jquery-ui.min.js')}}" type="text/javascript" charset="utf-8"></script>
<script src="{{url('js/bootstrap.min.js')}}" type="text/javascript" charset="utf-8"></script>
<script src="{{url('js/app.js')}}" type="text/javascript" charset="utf-8"></script>
<script src="{{url('js/bootstrap-datetimepicker.min.js')}}" type="text/javascript" charset="utf-8"></script>
@yield('load_assets')